#!/usr/bin/perl

use autodie;
use strict;
use feature 'say';
use List::Util qw(uniq);

open SYMBOLS, "<", "vkpfn_sym.txt";

use constant {
	GLOBAL => '$GLOBAL$',
	INSTANCE => '$INSTANCE$',
	DEVICE => '$DEVICE$'
};

my %sections = (
	GLOBAL, {},
	INSTANCE, {},
	DEVICE, {}
);
my $section = GLOBAL;

while (my $sym = <SYMBOLS>) {
	chomp $sym;

	if ($sym eq GLOBAL) { $section = GLOBAL; }
	elsif ($sym eq INSTANCE) { $section = INSTANCE; }
	elsif ($sym eq DEVICE) { $section = DEVICE; }
	elsif ($sym eq '') { next; }
	else {
		my @aliases = split ' ',$sym;
		my $symbol_name = shift(@aliases);
		my @suffixes = uniq @aliases;
		$sections{$section}->{$symbol_name} = \@suffixes;
	}
}

close SYMBOLS;

open HEADER, '>', 'vk_pfn.h';
open CODE, '>', 'vk_pfn.c';

say HEADER <<END;
/*** WARNING! This file is autogenerated, do not edit directly! ***/

#ifndef UBLC_VK_PFN
#define UBLC_VK_PFN 1

#define VK_NO_PROTOTYPES 1
#include <vulkan/vk_enum_string_helper.h>
#include <vulkan/vulkan.h>

#define VK_PFN_ALIAS(sym) asm("_" #sym "\$PTR")

void vkpfn_load_global(void);
void vkpfn_load_instance(VkInstance);
void vkpfn_load_device(VkDevice);

/* the one function we actually need linked */
PFN_vkVoidFunction vkGetInstanceProcAddr(VkInstance, const char *name);
END

say CODE <<END;
/*** WARNING! This file is autogenerated, do not edit directly! ***/

#include "vk_pfn.h"
END

say HEADER '/* global functions */';
say CODE '/* global functions */';

foreach my $key (sort keys %{$sections{'$GLOBAL$'}}) {
	say HEADER "extern PFN_$key $key VK_PFN_ALIAS($key);";
	say CODE "PFN_$key $key VK_PFN_ALIAS($key);";
}

say HEADER "\n/* instance functions */";
say CODE "\n/* instance functions */";

foreach my $key (sort keys %{$sections{'$INSTANCE$'}}) {
	say HEADER "extern PFN_$key $key VK_PFN_ALIAS($key);";
	say CODE "PFN_$key $key VK_PFN_ALIAS($key);";
}

say HEADER "\n/* device functions */";
say CODE "\n/* device functions */";

foreach my $key (sort keys %{$sections{'$DEVICE$'}}) {
	say HEADER "extern PFN_$key $key VK_PFN_ALIAS($key);";
	say CODE "PFN_$key $key VK_PFN_ALIAS($key);";
}

# header file's footer
say HEADER "\n#endif /* UBLC_VK_PFN */";

close HEADER;

# TODO: add suffixes implementation

say CODE "\nvoid vkpfn_load_global(void) {";

foreach my $key (sort keys %{$sections{'$GLOBAL$'}}) {
	print CODE <<END;
	$key = (void *)vkGetInstanceProcAddr(NULL, \"$key\");
END
}

say CODE "}\n";

say CODE 'void vkpfn_load_instance(VkInstance i) {';

foreach my $key (sort keys %{$sections{'$INSTANCE$'}}) {
	print CODE <<END;
	$key = (void *)vkGetInstanceProcAddr(i, \"$key\");
END
}

say CODE "}\n";

say CODE 'void vkpfn_load_device(VkDevice d) {';

foreach my $key (sort keys %{$sections{'$DEVICE$'}}) {
	print CODE <<END;
	$key = (void *)vkGetDeviceProcAddr(d, \"$key\");
END
}

say CODE '}';

close CODE;
