/*** WARNING! This file is autogenerated, do not edit directly! ***/

#ifndef UBLC_VK_PFN
#define UBLC_VK_PFN 1

#define VK_NO_PROTOTYPES 1
#include <vulkan/vk_enum_string_helper.h>
#include <vulkan/vulkan.h>

#define VK_PFN_ALIAS(sym) asm("_" #sym "$PTR")

void vkpfn_load_global(void);
void vkpfn_load_instance(VkInstance);
void vkpfn_load_device(VkDevice);

/* the one function we actually need linked */
PFN_vkVoidFunction vkGetInstanceProcAddr(VkInstance, const char *name);

/* global functions */
extern PFN_vkCreateInstance vkCreateInstance VK_PFN_ALIAS(vkCreateInstance);
extern PFN_vkEnumerateInstanceVersion vkEnumerateInstanceVersion VK_PFN_ALIAS(vkEnumerateInstanceVersion);

/* instance functions */
extern PFN_vkCreateDevice vkCreateDevice VK_PFN_ALIAS(vkCreateDevice);
extern PFN_vkDestroyInstance vkDestroyInstance VK_PFN_ALIAS(vkDestroyInstance);
extern PFN_vkEnumerateDeviceExtensionProperties vkEnumerateDeviceExtensionProperties VK_PFN_ALIAS(vkEnumerateDeviceExtensionProperties);
extern PFN_vkEnumeratePhysicalDevices vkEnumeratePhysicalDevices VK_PFN_ALIAS(vkEnumeratePhysicalDevices);
extern PFN_vkGetDeviceProcAddr vkGetDeviceProcAddr VK_PFN_ALIAS(vkGetDeviceProcAddr);
extern PFN_vkGetPhysicalDeviceProperties vkGetPhysicalDeviceProperties VK_PFN_ALIAS(vkGetPhysicalDeviceProperties);
extern PFN_vkGetPhysicalDeviceQueueFamilyProperties vkGetPhysicalDeviceQueueFamilyProperties VK_PFN_ALIAS(vkGetPhysicalDeviceQueueFamilyProperties);
extern PFN_vkGetPhysicalDeviceSurfaceSupportKHR vkGetPhysicalDeviceSurfaceSupportKHR VK_PFN_ALIAS(vkGetPhysicalDeviceSurfaceSupportKHR);

/* device functions */
extern PFN_vkCreateGraphicsPipelines vkCreateGraphicsPipelines VK_PFN_ALIAS(vkCreateGraphicsPipelines);
extern PFN_vkCreateShaderModule vkCreateShaderModule VK_PFN_ALIAS(vkCreateShaderModule);
extern PFN_vkDestroyDevice vkDestroyDevice VK_PFN_ALIAS(vkDestroyDevice);
extern PFN_vkDestroyPipeline vkDestroyPipeline VK_PFN_ALIAS(vkDestroyPipeline);
extern PFN_vkDestroyShaderModule vkDestroyShaderModule VK_PFN_ALIAS(vkDestroyShaderModule);

#endif /* UBLC_VK_PFN */
