#ifndef WORLD_MATERIAL_H
#define WORLD_MATERIAL_H 1

#define MATFL_NONE 0
#define MATFL_LIQUID (1 << 0)
#define MATFL_SOLID (1 << 1)
#define MATFL_BLOCKGRASS (1 << 2)
#define MATFL_BURNABLE (1 << 3)
#define MATFL_GROUNDCOVER (1 << 4)
#define MATFL_OPAQUE (1 << 5)
#define MATFL_HARVESTABLE (1 << 6)
#define MATFL_NOPUSH (1 << 7)
#define MATFL_IMMOVABLE (1 << 8)

#define MATERIAL_AIR MATFL_GROUNDCOVER
#define MATERIAL_GRASS (MATFL_SOLID | MATFL_BLOCKGRASS | MATFL_OPAQUE | \
		MATFL_HARVESTABLE)

#endif /* WORLD_MATERIAL_H */
